# Generated by Django 5.1.1 on 2024-09-09 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'verbose_name': 'Avaliação'},
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='comment',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3, 'Comentário deve ter, no mínimo, 3 caracteres.'), django.core.validators.MaxLengthValidator(500, 'Comentário não pode ter mais de 500 caracteres.')], verbose_name='Comentário'),
        ),
    ]
