# Generated by Django 5.1.1 on 2024-09-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_bookreview_options_alter_bookreview_comment'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='themes',
            field=models.ManyToManyField(related_name='books', to='themes.theme', verbose_name='Temas'),
        ),
    ]
