# Generated by Django 5.1.1 on 2024-09-10 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3, 'A descrição deve ter, no mínimo, 3 caracteres.'), django.core.validators.MaxLengthValidator(1000, 'A descrição do livro não pode ultrapassar 1000 caracteres.')], verbose_name='Descrição'),
        ),
    ]
