# Generated by Django 5.1.1 on 2024-09-12 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_description'),
        ('subgenres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subgenre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books', to='subgenres.subgenre', verbose_name='Subgênero'),
            preserve_default=False,
        ),
    ]
