# Generated by Django 5.1.1 on 2024-09-16 17:32

import books.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_subgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(validators=[books.validators.MaxDateValidator(datetime.datetime(2024, 9, 16, 14, 32, 51, 297802), 'A data não pode ser maior do que a atual.')], verbose_name='Data de Lançamento'),
        ),
    ]
