# Generated by Django 5.1.1 on 2024-09-18 14:10

import books.validators
import datetime
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_release_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookreview',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL, verbose_name='Curtidas'),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(validators=[books.validators.MaxDateValidator(datetime.datetime(2024, 9, 18, 11, 10, 17, 649381), 'A data não pode ser maior do que a atual.')], verbose_name='Data de Lançamento'),
        ),
    ]
