# Generated by Django 5.1.1 on 2024-09-19 17:10

import books.validators
import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_bookreview_created_at_bookreview_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avaliação'},
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(validators=[books.validators.MaxDateValidator(datetime.datetime(2024, 9, 19, 14, 10, 9, 26265), 'A data não pode ser maior do que a atual.')], verbose_name='Data de Lançamento'),
        ),
        migrations.AlterField(
            model_name='bookreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to=settings.AUTH_USER_MODEL, verbose_name='Curtidas'),
        ),
    ]
