# Generated by Django 5.1.1 on 2024-09-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('themes', models.ManyToManyField(related_name='genres', to='themes.theme', verbose_name='Temas')),
            ],
            options={
                'verbose_name': 'Gênero',
            },
        ),
    ]
