# Generated by Django 5.1.1 on 2024-09-10 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='themes',
        ),
    ]
