# Generated by Django 5.1.1 on 2024-09-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_remove_genre_themes'),
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='themes',
            field=models.ManyToManyField(related_name='genres', to='themes.theme', verbose_name='Temas'),
        ),
    ]
