# Generated by Django 5.1.1 on 2024-09-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_genre_themes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='themes',
        ),
    ]
