# Generated by Django 5.1.1 on 2024-09-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0004_remove_genre_themes'),
        ('subgenres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='subgenres',
            field=models.ManyToManyField(related_name='genres', to='subgenres.subgenre', verbose_name='Subgêneros'),
        ),
    ]
