# Generated by Django 5.1.1 on 2024-09-08 16:57

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=200, unique=True, verbose_name='Email')),
                ('website', models.URLField(blank=True, null=True, unique=True, verbose_name='Site da Editora')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Número de Telefone')),
            ],
            options={
                'verbose_name': 'Editora',
            },
        ),
    ]
